name: Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:  
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: go test -v -count=1 ./... -race -covermode=atomic -coverprofile=coverage.out

      - name: upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}